version: "3"
services:
  app:
    build: .
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "node api/api.js"
    ports:
      - "8083:8083"
    environment:
      PHP_IDE_CONFIG: serverName=test-app
    depends_on:
      - postgres
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
