CREATE USER requestuser WITH PASSWORD '**********';
GRANT SELECT ON MEASUREMENTS TO requestuser;
GRANT SELECT,UPDATE ON APIKEYS TO requestuser;
GRANT SELECT ON APIUSERS TO requestuser;
GRANT SELECT ON TAGS TO requestuser;
GRANT SELECT ON FLIGHTS TO requestuser;
GRANT USAGE ON "flights_flightId_seq" TO requestuser;

CREATE USER submituser WITH PASSWORD '**********';
GRANT SELECT,UPDATE,INSERT ON MEASUREMENTS TO submituser;
GRANT SELECT,UPDATE ON APIKEYS TO submituser;
GRANT SELECT,INSERT,DELETE ON APIUSERS TO submituser;
GRANT SELECT,INSERT ON TAGS TO submituser;
GRANT SELECT ON TILES TO submituser;
GRANT SELECT,UPDATE,INSERT ON FLIGHTS TO submituser;
GRANT SELECT,UPDATE,INSERT ON FLIGHTSTRACK TO submituser;
GRANT USAGE ON "flights_flightId_seq" TO submituser;
